version: "3.8"

services:
  web-chat:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - app-network
    restart: always
    entrypoint: >
      /bin/sh -c "
        ollama serve & 
        sleep 5 && 
        ollama run gemma3:1b &&
        wait
      "

networks:
  app-network:
    driver: bridge